/* eslint-disable */
// ----------------------------------------------------------------------------------------
// Do not edit this file, it is auto-generated by scripts/generate-version.js
// ----------------------------------------------------------------------------------------
export const APP_VERSION_INFO = Object.freeze({
  NAME: 'poc-archiver-expo',
  DISPLAY_NAME: 'ExpoPOC',
  DESCRIPTION: 'ReactNative Expo SDK POC collection',
  REPOSITORY: 'https://github.com/amwebexpert/poc-archiver-expo',
  AUTHOR: 'undefined',
  VERSION: '1.2.0',
  VERSION_DATE: '2025-01-01',
})

export const LONG_VERSION_DATE = '1.2.0 (2025-01-01)'
