/* eslint-disable */
// ----------------------------------------------------------------------------------------
// Do not edit this file, it is auto-generated by scripts/generate-version.js
// ----------------------------------------------------------------------------------------
export const APP_VERSION_INFO = Object.freeze({
  NAME: 'poc-archiver-expo',
  DESCRIPTION: 'undefined',
  REPOSITORY: 'undefined',
  AUTHOR: 'undefined',
  VERSION: '1.1.0',
  VERSION_DATE: '2024-12-24',
})

export const LONG_VERSION_DATE = '1.1.0 (2024-12-24)'
